name: deploy-v3

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    container:
      image: node:18

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Clone and install dependencies for ViewersV3
        run: |
          git clone https://github.com/ImagingDataCommons/ViewersV3.git
          cd ViewersV3
          yarn install --frozen-lockfile

      - name: Link repos and build ViewersV3
        run: |
          cd ViewersV3
          wget -O ./firebase.json "${{ vars.FIREBASE_JSON_URL }}"
          yarn build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: viewers-sandbox-gha-testing
          entryPoint: ./ViewersV3
          channelId: live 
          # channelId: # 'pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'