name: deploy-v3-with-add-ons

on:
  workflow_dispatch:

jobs:
  link_build_and_deploy:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Clone and install dependencies for ViewersV3
        run: |
          git clone https://github.com/ImagingDataCommons/ViewersV3.git
          cd ViewersV3
          yarn install --frozen-lockfile

      - name: Clone and install dependencies for ohif-gcp-mode
        run: |
          git clone https://github.com/ImagingDataCommons/ohif-gcp-mode.git
          cd ohif-gcp-mode
          yarn install --frozen-lockfile
          yarn link

      - name: Clone and install dependencies for ohif-gcp-extension
        run: |
          git clone https://github.com/ImagingDataCommons/ohif-gcp-extension.git
          cd ohif-gcp-extension
          yarn install --frozen-lockfile
          yarn link

      - name: Link repos and build ViewersV3
        run: |
          cd ViewersV3
          wget -O ./firebase.json "${{ vars.FIREBASE_JSON_URL }}"
          yarn link ohif-gcp-mode
          yarn link ohif-gcp-extension
          yarn build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: viewers-sandbox-gha-testing
          entryPoint: ./ViewersV3
          channelId: live 
          # channelId: # 'pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'